version: "3.9"

services:
  redis:
    image: redis:7.2.1
    ports:
      - 6379:6379

  db:
    image: postgres:15.4
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
