version: "3.9"

services:
  redis:
    image: redis:7.4.1
    ports:
      - 6379:6379

  db:
    image: postgres:16.0
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
