version: "3.9"
services:
  redis:
    image: redis:7.0.10
    ports:
      - 6379:6379
  db:
    image: postgres:15.2
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

