version: "3.9"
services:
  redis:
    image: redis:7.0.9
    ports:
      - 6379:6379
  db:
    image: postgres:15.2
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      ./.env
    ports:
      - 5432:5432