name: Build Docker image

on:
  push:
  pull_request:

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        target: ["frontend", "backend"]
    defaults:
      run:
        working-directory: ${{ matrix.target }}

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2

      - name: Define image name suffix if necessary
        if: ${{ github.event_name == 'pull_request' }}
        id: image_suffix
        run:
          echo "image_suffix=/test" >> "$GITHUB_OUTPUT"

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository_owner }}/elephas/${{ matrix.target }}${{ steps.image_suffix.outputs.image_suffix }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
