name: Test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  CARGO_INCREMENTAL: 0

defaults:
  run:
    working-directory: backend

jobs:
  check:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check format
        run: cargo fmt -- --check

      - name: Build
        run: cargo build --locked --verbose

      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings

  unittest:
    runs-on: 'ubuntu-22.04'
    services:
      postgres:
        image: 'postgres:15.2'
        env:
          POSTGRES_DB: test
          POSTGRES_USER: ikanago
          POSTGRES_PASSWORD: password
    env:
      DATABASE_URL: 'postgresql://ikanago:password@localhost:5432/test?schema=public'

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --locked --verbose

      - name: Run tests
        run: cargo test --verbose
