name: Test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  CARGO_INCREMENTAL: 0

jobs:
  backend_test:
    runs-on: 'ubuntu-22.04'
    services:
      redis:
        image: 'redis:7.0.8'
        ports:
          - 6379:6379
      postgres:
        image: 'postgres:15.2'
        env:
          POSTGRES_DB: test
          POSTGRES_USER: ikanago
          POSTGRES_PASSWORD: password
          POSTGRES_INITDB_ARGS: '--encoding=UTF8'
        ports:
          - 5432:5432
    env:
      COOKIE_KEY: 'KuNBwnCNhJWdqlVLB2ZJ/1jrQtV3T82c4ds8NS+MIQ4wyVDah5cFbNVZzZrxw2PrvEEhWrZPrmgyvjSF6Qj9Vg=='
      DATABASE_URL: 'postgresql://ikanago:password@localhost:5432/test'
      REDIS_URL: 'localhost:6379'
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend -> target

      - name: Setup Postgresql
        run: psql ${DATABASE_URL} < ./migrations/20230222011102_init.sql

      - name: Build and test
        run: |
          cargo build --locked --verbose
          cargo test --verbose

      - name: Cache frontend dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/Cypress
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install frontend dependencies and build
        run: |
          npm ci
          npm run build
        working-directory: frontend

      - name: Run e2e tests
        run: |
          cargo run &
          cd ../frontend
          npm run e2e:ci

  frontend_test:
    runs-on: 'ubuntu-22.04'
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
