name: Test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  CARGO_INCREMENTAL: 0

jobs:
  backend_test:
    runs-on: 'ubuntu-22.04'
    services:
      postgres:
        image: 'postgres:15.2'
        env:
          POSTGRES_DB: test
          POSTGRES_USER: ikanago
          POSTGRES_PASSWORD: password
          POSTGRES_INITDB_ARGS: "--encoding=UTF8"
        ports:
          - 5432:5432
    env:
      DATABASE_URL: 'postgresql://ikanago:password@localhost:5432/test'
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend -> target

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Setup Postgresql
        run: psql ${DATABASE_URL} < ./migrations/20230222011102_init.sql

      - name: Build
        run: cargo build --locked --verbose

      - name: Run tests
        run: cargo test --verbose
